### PR TITLE
Adding some examples to the README.

### PR DESCRIPTION
**Pull request by kayakyakr**
Since ActionCable is an engine, it can be run in-app in the same way that websocket-rails can be (and I will admit to shamelessly stealing the implementation from websocket rails). Also adding examples of passing params to subscription and rebroadcasting received message.

### CODE REVIEW

**Comment by dhh** [comment]
Lovely!

**Comment by dhh** [comment]
We can definitely use your help to flesh out the documentation even more.

**Comment by kayakyakr** [comment]
Sure thing. I'm probably going to be running ActionCable in staging later today and, if all goes well, in production (alpha/beta software) later this week. Be happy to add documentation as I find things.

**Comment by dhh** [comment]
Perfect!

**Pull request merged**
