### PR TITLE
Add contributing file

### PR DESCRIPTION
**Pull request by maclover7**
cc @dhh

### CODE REVIEW

**Comment by dhh** [comment]
Nice. Is it actually true that we already have "hundreds of contributors"?

**Comment by maclover7** [comment]
Lol - am just using the same template across all Rails sub projects. There are only 19 contributors to ActionCable, including yourself and myself.

**Comment by dhh** [comment]
Then maybe just go with "the many" or "lots" or something like that.

**Comment by matthewd** [comment]
I don't think we need to do this; actioncable will be merged into rails/rails soon enough, and the other components don't have separate contributing files.

**Comment by dhh** [comment]
Even better.

**Pull request closed without merging**
