### PR TITLE
create adapter system

### PR DESCRIPTION
**Pull request by meinac**
The idea comes from #28 
/cc @guilleiguaran , @dhh

### CODE REVIEW

**Comment by matthewd** [comment]
There seems to be too many layers of indirection here.

`Broadcaster` contains a `@broadcaster`, which it populates by calling `Redis::Broadcaster.new.broadcaster` ? :confused:

**Comment by dhh** [comment]
Yeah, appreciate the initial work here, but this isn't quite right. Going to take a stab at this shortly.

**Comment by cristianbica** [comment]
@dhh do you want something like [this](https://github.com/rails/actioncable/compare/rails:master...cristianbica:adapter)?
Then we would have a `ActionCable::Base.connection` which will be an instance of an adapter and it will be used across classes.
I would also like to have an AR style configuration `config/action_cable.yml` or `ENV['ACTION_CABLE_BACKEND_URL']`

**Comment by inopinatus** [comment]
Hoping we can incorporate postgresql's native pub/sub as one such adapter. Minimising the external infrastructure dependencies will be a win for lean startups.

**Comment by rafaelfranca** [comment]
Closing since it is not the direction that we want to take.

**Comment by meinac** [comment]
@rafaelfranca, in the current implementation of this feature it depends on redis, but as @inopinatus mentioned as a developer if I want to use postgre as pubsub agent there is no solution for this. In this pr I wanted to separate pubsub agent like an activerecord adapter to give direction to open source developers to implement their third party adapters so they can implement adapters like aws sqs, postgresql, rabbitmq or whatever they like. This pr does not aim to implement another agent in itself, it's aim is only create a way for developers to implement their adapters.
By this pr, opensource developers can create their own adapters for their favorite pubsub agent and I think this is important to give developers to use existing infrastructure as pubsub agent.

**Pull request closed without merging**
