### PR TITLE
Add coffee-rails as a dependency.

### PR DESCRIPTION
**Pull request by constXife**

### CODE REVIEW

**Comment by seuros** [comment]
CS is not a dependency of ACable. You can use plain js if you wish.

**Comment by matthewd** [comment]
Do we need to be so particular about the version? [Turbolinks, for example,](https://github.com/rails/turbolinks/blob/master/turbolinks.gemspec#L14) leaves the versioning up to coffee-rails itself.

**Comment by constXife** [comment]
@seuros, i'd like to. But in actioncable/lib/assets/javascripts I see only coffee files. 
@matthewd, you're right.

**Comment by seuros** [comment]
@constXife yes, but CS is not a dependency. You can rename and use js or anything that generate javascript in the end.

**Comment by rafaelfranca** [comment]
> yes, but CS is not a dependency.

Yes, it is. Users can't use this gem's  JavaScript code without coffee-script.

**Pull request merged**
